using Microsoft.EntityFrameworkCore;
using ShopForge.Database.Entities;

namespace ShopForge.Database.SeedData;

public static class ProductSeedData
{
    public static void Seed(ModelBuilder modelBuilder)
    {
        var now = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        modelBuilder.Entity<Product>().HasData(
            // ── Electronics (CategoryId=1, BrandId=1) ──────────────────────────
            new Product { Id = 1,  Name = "4K Smart TV 55\"",           Slug = "4k-smart-tv-55",            SKU = "ELEC-001", Price = 15999m, StockQuantity = 25, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = true,  CreatedAt = now, UpdatedAt = now },
            new Product { Id = 2,  Name = "Laptop Pro 15\"",             Slug = "laptop-pro-15",             SKU = "ELEC-002", Price = 22999m, StockQuantity = 15, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 3,  Name = "Wireless Headphones",         Slug = "wireless-headphones",       SKU = "ELEC-003", Price = 2499m,  StockQuantity = 50, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 4,  Name = "Smartphone X12",              Slug = "smartphone-x12",            SKU = "ELEC-004", Price = 12999m, StockQuantity = 30, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 5,  Name = "Bluetooth Speaker",           Slug = "bluetooth-speaker",         SKU = "ELEC-005", Price = 1299m,  StockQuantity = 60, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 6,  Name = "Gaming Console",              Slug = "gaming-console",            SKU = "ELEC-006", Price = 9999m,  StockQuantity = 20, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 7,  Name = "Tablet 10\"",                 Slug = "tablet-10",                 SKU = "ELEC-007", Price = 6999m,  StockQuantity = 35, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 8,  Name = "Smartwatch Series 5",         Slug = "smartwatch-series-5",       SKU = "ELEC-008", Price = 3999m,  StockQuantity = 40, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 9,  Name = "Wireless Earbuds",            Slug = "wireless-earbuds",          SKU = "ELEC-009", Price = 1999m,  StockQuantity = 70, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 10, Name = "Digital Camera 24MP",         Slug = "digital-camera-24mp",       SKU = "ELEC-010", Price = 8999m,  StockQuantity = 18, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 11, Name = "USB-C Hub 7-in-1",            Slug = "usb-c-hub-7in1",            SKU = "ELEC-011", Price = 599m,   StockQuantity = 80, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 12, Name = "Mechanical Keyboard",         Slug = "mechanical-keyboard",       SKU = "ELEC-012", Price = 1499m,  StockQuantity = 45, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 13, Name = "Gaming Mouse",                Slug = "gaming-mouse",              SKU = "ELEC-013", Price = 899m,   StockQuantity = 55, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 14, Name = "27\" Monitor",                Slug = "monitor-27",                SKU = "ELEC-014", Price = 5999m,  StockQuantity = 22, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 15, Name = "Portable Charger 20000mAh",   Slug = "portable-charger-20000mah", SKU = "ELEC-015", Price = 499m,   StockQuantity = 90, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 16, Name = "Wi-Fi Router AC3000",         Slug = "wifi-router-ac3000",        SKU = "ELEC-016", Price = 1899m,  StockQuantity = 28, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 17, Name = "NAS Drive 4TB",               Slug = "nas-drive-4tb",             SKU = "ELEC-017", Price = 4999m,  StockQuantity = 12, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 18, Name = "VR Headset",                  Slug = "vr-headset",                SKU = "ELEC-018", Price = 7999m,  StockQuantity = 10, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 19, Name = "Drone with Camera",           Slug = "drone-with-camera",         SKU = "ELEC-019", Price = 11999m, StockQuantity = 8,  CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 20, Name = "Smart Home Hub",              Slug = "smart-home-hub",            SKU = "ELEC-020", Price = 1299m,  StockQuantity = 35, CategoryId = 1, BrandId = 1, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },

            // ── Clothing & Apparel (CategoryId=2, BrandId=2) ───────────────────
            new Product { Id = 21, Name = "Men's Slim Fit Jeans",        Slug = "mens-slim-fit-jeans",       SKU = "CLTH-001", Price = 699m,  StockQuantity = 80, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = true,  CreatedAt = now, UpdatedAt = now },
            new Product { Id = 22, Name = "Women's Summer Dress",        Slug = "womens-summer-dress",       SKU = "CLTH-002", Price = 599m,  StockQuantity = 60, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 23, Name = "Unisex Hoodie",               Slug = "unisex-hoodie",             SKU = "CLTH-003", Price = 499m,  StockQuantity = 100,CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 24, Name = "Men's Business Shirt",        Slug = "mens-business-shirt",       SKU = "CLTH-004", Price = 449m,  StockQuantity = 70, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 25, Name = "Women's Yoga Leggings",       Slug = "womens-yoga-leggings",      SKU = "CLTH-005", Price = 399m,  StockQuantity = 90, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 26, Name = "Men's Polo Shirt",            Slug = "mens-polo-shirt",           SKU = "CLTH-006", Price = 349m,  StockQuantity = 85, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 27, Name = "Women's Blazer",              Slug = "womens-blazer",             SKU = "CLTH-007", Price = 899m,  StockQuantity = 40, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 28, Name = "Men's Chino Pants",           Slug = "mens-chino-pants",          SKU = "CLTH-008", Price = 599m,  StockQuantity = 65, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 29, Name = "Women's Denim Jacket",        Slug = "womens-denim-jacket",       SKU = "CLTH-009", Price = 799m,  StockQuantity = 50, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 30, Name = "Men's Cargo Shorts",          Slug = "mens-cargo-shorts",         SKU = "CLTH-010", Price = 449m,  StockQuantity = 75, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 31, Name = "Women's Cardigan",            Slug = "womens-cardigan",           SKU = "CLTH-011", Price = 549m,  StockQuantity = 55, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 32, Name = "Men's V-Neck Sweater",        Slug = "mens-vneck-sweater",        SKU = "CLTH-012", Price = 499m,  StockQuantity = 60, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 33, Name = "Women's Mini Skirt",          Slug = "womens-mini-skirt",         SKU = "CLTH-013", Price = 349m,  StockQuantity = 70, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 34, Name = "Men's Tracksuit",             Slug = "mens-tracksuit",            SKU = "CLTH-014", Price = 799m,  StockQuantity = 45, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 35, Name = "Women's Windbreaker",         Slug = "womens-windbreaker",        SKU = "CLTH-015", Price = 699m,  StockQuantity = 40, CategoryId = 2, BrandId = 2, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },

            // ── Home & Garden (CategoryId=3, BrandId=3) ────────────────────────
            new Product { Id = 36, Name = "Coffee Table Oak",            Slug = "coffee-table-oak",          SKU = "HOME-001", Price = 2999m, StockQuantity = 15, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = true,  CreatedAt = now, UpdatedAt = now },
            new Product { Id = 37, Name = "Queen Bed Frame",             Slug = "queen-bed-frame",           SKU = "HOME-002", Price = 4999m, StockQuantity = 10, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 38, Name = "Floor Lamp Modern",           Slug = "floor-lamp-modern",         SKU = "HOME-003", Price = 799m,  StockQuantity = 30, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 39, Name = "Wall Clock Minimalist",       Slug = "wall-clock-minimalist",     SKU = "HOME-004", Price = 349m,  StockQuantity = 50, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 40, Name = "Throw Pillow Set 4pc",        Slug = "throw-pillow-set-4pc",      SKU = "HOME-005", Price = 299m,  StockQuantity = 60, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 41, Name = "Kitchen Knife Set 7pc",       Slug = "kitchen-knife-set-7pc",     SKU = "HOME-006", Price = 999m,  StockQuantity = 35, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 42, Name = "Non-Stick Cookware Set",      Slug = "non-stick-cookware-set",    SKU = "HOME-007", Price = 1799m, StockQuantity = 20, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 43, Name = "Garden Hose 30m",             Slug = "garden-hose-30m",           SKU = "HOME-008", Price = 399m,  StockQuantity = 40, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 44, Name = "Ceramic Indoor Plant Pot",    Slug = "ceramic-plant-pot",         SKU = "HOME-009", Price = 199m,  StockQuantity = 80, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 45, Name = "Blackout Curtain Set",        Slug = "blackout-curtain-set",      SKU = "HOME-010", Price = 599m,  StockQuantity = 45, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 46, Name = "Bath Towel Set 6pc",          Slug = "bath-towel-set-6pc",        SKU = "HOME-011", Price = 449m,  StockQuantity = 55, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 47, Name = "Waterproof Shower Curtain",   Slug = "waterproof-shower-curtain", SKU = "HOME-012", Price = 249m,  StockQuantity = 65, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 48, Name = "Bamboo Desk Organizer",       Slug = "bamboo-desk-organizer",     SKU = "HOME-013", Price = 299m,  StockQuantity = 70, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 49, Name = "Bookshelf 5-Tier",            Slug = "bookshelf-5-tier",          SKU = "HOME-014", Price = 1499m, StockQuantity = 18, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 50, Name = "Non-Slip Doormat",            Slug = "non-slip-doormat",          SKU = "HOME-015", Price = 149m,  StockQuantity = 90, CategoryId = 3, BrandId = 3, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },

            // ── Sports & Outdoors (CategoryId=4, BrandId=4) ────────────────────
            new Product { Id = 51, Name = "Premium Yoga Mat",            Slug = "premium-yoga-mat",          SKU = "SPRT-001", Price = 399m,  StockQuantity = 60, CategoryId = 4, BrandId = 4, IsActive = true, IsFeatured = true,  CreatedAt = now, UpdatedAt = now },
            new Product { Id = 52, Name = "Adjustable Dumbbell Set 20kg",Slug = "adjustable-dumbbell-set",   SKU = "SPRT-002", Price = 1999m, StockQuantity = 20, CategoryId = 4, BrandId = 4, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 53, Name = "Trail Running Shoes",         Slug = "trail-running-shoes",       SKU = "SPRT-003", Price = 1299m, StockQuantity = 40, CategoryId = 4, BrandId = 4, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 54, Name = "Sports Gym Bag 40L",          Slug = "sports-gym-bag-40l",        SKU = "SPRT-004", Price = 549m,  StockQuantity = 55, CategoryId = 4, BrandId = 4, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 55, Name = "Resistance Bands Set 5pc",    Slug = "resistance-bands-set",      SKU = "SPRT-005", Price = 249m,  StockQuantity = 80, CategoryId = 4, BrandId = 4, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 56, Name = "Speed Jump Rope",             Slug = "speed-jump-rope",           SKU = "SPRT-006", Price = 149m,  StockQuantity = 100,CategoryId = 4, BrandId = 4, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 57, Name = "Cycling Safety Helmet",       Slug = "cycling-safety-helmet",     SKU = "SPRT-007", Price = 799m,  StockQuantity = 30, CategoryId = 4, BrandId = 4, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 58, Name = "Insulated Water Bottle 1L",   Slug = "insulated-water-bottle-1l", SKU = "SPRT-008", Price = 299m,  StockQuantity = 75, CategoryId = 4, BrandId = 4, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 59, Name = "Tennis Racket Pro",           Slug = "tennis-racket-pro",         SKU = "SPRT-009", Price = 899m,  StockQuantity = 25, CategoryId = 4, BrandId = 4, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 60, Name = "Match Football Size 5",       Slug = "match-football-size-5",     SKU = "SPRT-010", Price = 349m,  StockQuantity = 50, CategoryId = 4, BrandId = 4, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },

            // ── Books & Media (CategoryId=5, BrandId=5) ────────────────────────
            new Product { Id = 61, Name = "The Art of Clean Coding",     Slug = "art-of-clean-coding",       SKU = "BOOK-001", Price = 349m, StockQuantity = 50, CategoryId = 5, BrandId = 5, IsActive = true, IsFeatured = true,  CreatedAt = now, UpdatedAt = now },
            new Product { Id = 62, Name = "Business Strategy 101",       Slug = "business-strategy-101",     SKU = "BOOK-002", Price = 299m, StockQuantity = 45, CategoryId = 5, BrandId = 5, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 63, Name = "Mindfulness for Beginners",   Slug = "mindfulness-for-beginners", SKU = "BOOK-003", Price = 249m, StockQuantity = 60, CategoryId = 5, BrandId = 5, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 64, Name = "The Cooking Masterclass",     Slug = "cooking-masterclass",       SKU = "BOOK-004", Price = 449m, StockQuantity = 35, CategoryId = 5, BrandId = 5, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 65, Name = "World History Encyclopedia",  Slug = "world-history-encyclopedia",SKU = "BOOK-005", Price = 699m, StockQuantity = 20, CategoryId = 5, BrandId = 5, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 66, Name = "Science Fiction Anthology",   Slug = "science-fiction-anthology", SKU = "BOOK-006", Price = 199m, StockQuantity = 70, CategoryId = 5, BrandId = 5, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 67, Name = "Children's Adventure Series", Slug = "childrens-adventure-series",SKU = "BOOK-007", Price = 249m, StockQuantity = 55, CategoryId = 5, BrandId = 5, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 68, Name = "Photography Basics Guide",    Slug = "photography-basics-guide",  SKU = "BOOK-008", Price = 349m, StockQuantity = 30, CategoryId = 5, BrandId = 5, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 69, Name = "Financial Freedom Guide",     Slug = "financial-freedom-guide",   SKU = "BOOK-009", Price = 299m, StockQuantity = 40, CategoryId = 5, BrandId = 5, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 70, Name = "Language Learning Pack",      Slug = "language-learning-pack",    SKU = "BOOK-010", Price = 549m, StockQuantity = 25, CategoryId = 5, BrandId = 5, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },

            // ── Health & Beauty (CategoryId=6, BrandId=6) ──────────────────────
            new Product { Id = 71, Name = "Daily Multivitamin Complex",      Slug = "daily-multivitamin-complex",     SKU = "HLTH-001", Price = 299m, StockQuantity = 80, CategoryId = 6, BrandId = 6, IsActive = true, IsFeatured = true,  CreatedAt = now, UpdatedAt = now },
            new Product { Id = 72, Name = "Whey Protein Powder 1kg",         Slug = "whey-protein-powder-1kg",        SKU = "HLTH-002", Price = 699m, StockQuantity = 50, CategoryId = 6, BrandId = 6, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 73, Name = "Face Moisturizer SPF30",          Slug = "face-moisturizer-spf30",         SKU = "HLTH-003", Price = 349m, StockQuantity = 70, CategoryId = 6, BrandId = 6, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 74, Name = "Hair Growth Serum",               Slug = "hair-growth-serum",              SKU = "HLTH-004", Price = 449m, StockQuantity = 45, CategoryId = 6, BrandId = 6, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 75, Name = "Sonic Electric Toothbrush",       Slug = "sonic-electric-toothbrush",      SKU = "HLTH-005", Price = 799m, StockQuantity = 35, CategoryId = 6, BrandId = 6, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 76, Name = "Digital Infrared Thermometer",    Slug = "digital-infrared-thermometer",   SKU = "HLTH-006", Price = 299m, StockQuantity = 60, CategoryId = 6, BrandId = 6, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 77, Name = "Automatic Blood Pressure Monitor",Slug = "blood-pressure-monitor",         SKU = "HLTH-007", Price = 999m, StockQuantity = 25, CategoryId = 6, BrandId = 6, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 78, Name = "Muscle Recovery Foam Roller",     Slug = "muscle-recovery-foam-roller",    SKU = "HLTH-008", Price = 349m, StockQuantity = 55, CategoryId = 6, BrandId = 6, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 79, Name = "Aromatherapy Diffuser",           Slug = "aromatherapy-diffuser",          SKU = "HLTH-009", Price = 499m, StockQuantity = 40, CategoryId = 6, BrandId = 6, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 80, Name = "Melatonin Sleep Supplement",      Slug = "melatonin-sleep-supplement",     SKU = "HLTH-010", Price = 199m, StockQuantity = 75, CategoryId = 6, BrandId = 6, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },

            // ── Toys & Games (CategoryId=7, BrandId=7) ─────────────────────────
            new Product { Id = 81, Name = "LEGO City Police Station",    Slug = "lego-city-police-station",  SKU = "TOYS-001", Price = 1499m, StockQuantity = 20, CategoryId = 7, BrandId = 7, IsActive = true, IsFeatured = true,  CreatedAt = now, UpdatedAt = now },
            new Product { Id = 82, Name = "RC Off-Road Car 1:16",        Slug = "rc-off-road-car",           SKU = "TOYS-002", Price = 799m,  StockQuantity = 30, CategoryId = 7, BrandId = 7, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 83, Name = "Classic Monopoly Board Game", Slug = "classic-monopoly-game",     SKU = "TOYS-003", Price = 499m,  StockQuantity = 50, CategoryId = 7, BrandId = 7, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 84, Name = "Giant Stuffed Teddy Bear",    Slug = "giant-stuffed-teddy-bear",  SKU = "TOYS-004", Price = 399m,  StockQuantity = 35, CategoryId = 7, BrandId = 7, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 85, Name = "Premium 1000-Piece Puzzle",   Slug = "premium-1000-piece-puzzle", SKU = "TOYS-005", Price = 249m,  StockQuantity = 60, CategoryId = 7, BrandId = 7, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 86, Name = "Watercolor Art Set 48pc",     Slug = "watercolor-art-set-48pc",   SKU = "TOYS-006", Price = 349m,  StockQuantity = 45, CategoryId = 7, BrandId = 7, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 87, Name = "Junior Science Kit",          Slug = "junior-science-kit",        SKU = "TOYS-007", Price = 449m,  StockQuantity = 25, CategoryId = 7, BrandId = 7, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 88, Name = "Wooden Building Blocks 50pc", Slug = "wooden-building-blocks",    SKU = "TOYS-008", Price = 299m,  StockQuantity = 55, CategoryId = 7, BrandId = 7, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 89, Name = "Deluxe Doll House",           Slug = "deluxe-doll-house",         SKU = "TOYS-009", Price = 1299m, StockQuantity = 15, CategoryId = 7, BrandId = 7, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 90, Name = "Elite Nerf Blaster Set",      Slug = "elite-nerf-blaster-set",    SKU = "TOYS-010", Price = 649m,  StockQuantity = 40, CategoryId = 7, BrandId = 7, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },

            // ── Food & Grocery (CategoryId=8, BrandId=8) ───────────────────────
            new Product { Id = 91,  Name = "Organic Fair Trade Coffee 500g", Slug = "organic-coffee-500g",         SKU = "FOOD-001", Price = 199m, StockQuantity = 80, CategoryId = 8, BrandId = 8, IsActive = true, IsFeatured = true,  CreatedAt = now, UpdatedAt = now },
            new Product { Id = 92,  Name = "Premium Dark Chocolate Box",     Slug = "premium-dark-chocolate-box",  SKU = "FOOD-002", Price = 149m, StockQuantity = 90, CategoryId = 8, BrandId = 8, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 93,  Name = "Raw Honey 1kg",                  Slug = "raw-honey-1kg",               SKU = "FOOD-003", Price = 249m, StockQuantity = 70, CategoryId = 8, BrandId = 8, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 94,  Name = "Mixed Nuts and Seeds 500g",      Slug = "mixed-nuts-seeds-500g",       SKU = "FOOD-004", Price = 189m, StockQuantity = 85, CategoryId = 8, BrandId = 8, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 95,  Name = "Premium Green Tea 50 Bags",      Slug = "premium-green-tea-50bags",    SKU = "FOOD-005", Price = 149m, StockQuantity = 100,CategoryId = 8, BrandId = 8, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 96,  Name = "Artisan Pasta Variety Box",      Slug = "artisan-pasta-variety-box",   SKU = "FOOD-006", Price = 249m, StockQuantity = 75, CategoryId = 8, BrandId = 8, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 97,  Name = "Extra Virgin Olive Oil 1L",      Slug = "extra-virgin-olive-oil-1l",   SKU = "FOOD-007", Price = 199m, StockQuantity = 80, CategoryId = 8, BrandId = 8, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 98,  Name = "Granola Breakfast Mix 500g",     Slug = "granola-breakfast-mix-500g",  SKU = "FOOD-008", Price = 169m, StockQuantity = 90, CategoryId = 8, BrandId = 8, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 99,  Name = "Protein Snack Bars 12-Pack",     Slug = "protein-snack-bars-12pack",   SKU = "FOOD-009", Price = 299m, StockQuantity = 65, CategoryId = 8, BrandId = 8, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now },
            new Product { Id = 100, Name = "World Spice Collection Set",      Slug = "world-spice-collection-set",  SKU = "FOOD-010", Price = 449m, StockQuantity = 50, CategoryId = 8, BrandId = 8, IsActive = true, IsFeatured = false, CreatedAt = now, UpdatedAt = now }
        );

        // ── Product Images (one primary image per product) ──────────────────────
        modelBuilder.Entity<ProductImage>().HasData(
            new ProductImage { Id = 1,   ProductId = 1,   ImageUrl = "https://picsum.photos/seed/ELEC-001/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 2,   ProductId = 2,   ImageUrl = "https://picsum.photos/seed/ELEC-002/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 3,   ProductId = 3,   ImageUrl = "https://picsum.photos/seed/ELEC-003/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 4,   ProductId = 4,   ImageUrl = "https://picsum.photos/seed/ELEC-004/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 5,   ProductId = 5,   ImageUrl = "https://picsum.photos/seed/ELEC-005/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 6,   ProductId = 6,   ImageUrl = "https://picsum.photos/seed/ELEC-006/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 7,   ProductId = 7,   ImageUrl = "https://picsum.photos/seed/ELEC-007/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 8,   ProductId = 8,   ImageUrl = "https://picsum.photos/seed/ELEC-008/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 9,   ProductId = 9,   ImageUrl = "https://picsum.photos/seed/ELEC-009/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 10,  ProductId = 10,  ImageUrl = "https://picsum.photos/seed/ELEC-010/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 11,  ProductId = 11,  ImageUrl = "https://picsum.photos/seed/ELEC-011/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 12,  ProductId = 12,  ImageUrl = "https://picsum.photos/seed/ELEC-012/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 13,  ProductId = 13,  ImageUrl = "https://picsum.photos/seed/ELEC-013/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 14,  ProductId = 14,  ImageUrl = "https://picsum.photos/seed/ELEC-014/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 15,  ProductId = 15,  ImageUrl = "https://picsum.photos/seed/ELEC-015/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 16,  ProductId = 16,  ImageUrl = "https://picsum.photos/seed/ELEC-016/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 17,  ProductId = 17,  ImageUrl = "https://picsum.photos/seed/ELEC-017/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 18,  ProductId = 18,  ImageUrl = "https://picsum.photos/seed/ELEC-018/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 19,  ProductId = 19,  ImageUrl = "https://picsum.photos/seed/ELEC-019/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 20,  ProductId = 20,  ImageUrl = "https://picsum.photos/seed/ELEC-020/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 21,  ProductId = 21,  ImageUrl = "https://picsum.photos/seed/CLTH-001/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 22,  ProductId = 22,  ImageUrl = "https://picsum.photos/seed/CLTH-002/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 23,  ProductId = 23,  ImageUrl = "https://picsum.photos/seed/CLTH-003/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 24,  ProductId = 24,  ImageUrl = "https://picsum.photos/seed/CLTH-004/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 25,  ProductId = 25,  ImageUrl = "https://picsum.photos/seed/CLTH-005/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 26,  ProductId = 26,  ImageUrl = "https://picsum.photos/seed/CLTH-006/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 27,  ProductId = 27,  ImageUrl = "https://picsum.photos/seed/CLTH-007/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 28,  ProductId = 28,  ImageUrl = "https://picsum.photos/seed/CLTH-008/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 29,  ProductId = 29,  ImageUrl = "https://picsum.photos/seed/CLTH-009/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 30,  ProductId = 30,  ImageUrl = "https://picsum.photos/seed/CLTH-010/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 31,  ProductId = 31,  ImageUrl = "https://picsum.photos/seed/CLTH-011/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 32,  ProductId = 32,  ImageUrl = "https://picsum.photos/seed/CLTH-012/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 33,  ProductId = 33,  ImageUrl = "https://picsum.photos/seed/CLTH-013/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 34,  ProductId = 34,  ImageUrl = "https://picsum.photos/seed/CLTH-014/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 35,  ProductId = 35,  ImageUrl = "https://picsum.photos/seed/CLTH-015/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 36,  ProductId = 36,  ImageUrl = "https://picsum.photos/seed/HOME-001/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 37,  ProductId = 37,  ImageUrl = "https://picsum.photos/seed/HOME-002/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 38,  ProductId = 38,  ImageUrl = "https://picsum.photos/seed/HOME-003/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 39,  ProductId = 39,  ImageUrl = "https://picsum.photos/seed/HOME-004/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 40,  ProductId = 40,  ImageUrl = "https://picsum.photos/seed/HOME-005/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 41,  ProductId = 41,  ImageUrl = "https://picsum.photos/seed/HOME-006/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 42,  ProductId = 42,  ImageUrl = "https://picsum.photos/seed/HOME-007/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 43,  ProductId = 43,  ImageUrl = "https://picsum.photos/seed/HOME-008/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 44,  ProductId = 44,  ImageUrl = "https://picsum.photos/seed/HOME-009/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 45,  ProductId = 45,  ImageUrl = "https://picsum.photos/seed/HOME-010/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 46,  ProductId = 46,  ImageUrl = "https://picsum.photos/seed/HOME-011/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 47,  ProductId = 47,  ImageUrl = "https://picsum.photos/seed/HOME-012/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 48,  ProductId = 48,  ImageUrl = "https://picsum.photos/seed/HOME-013/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 49,  ProductId = 49,  ImageUrl = "https://picsum.photos/seed/HOME-014/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 50,  ProductId = 50,  ImageUrl = "https://picsum.photos/seed/HOME-015/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 51,  ProductId = 51,  ImageUrl = "https://picsum.photos/seed/SPRT-001/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 52,  ProductId = 52,  ImageUrl = "https://picsum.photos/seed/SPRT-002/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 53,  ProductId = 53,  ImageUrl = "https://picsum.photos/seed/SPRT-003/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 54,  ProductId = 54,  ImageUrl = "https://picsum.photos/seed/SPRT-004/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 55,  ProductId = 55,  ImageUrl = "https://picsum.photos/seed/SPRT-005/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 56,  ProductId = 56,  ImageUrl = "https://picsum.photos/seed/SPRT-006/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 57,  ProductId = 57,  ImageUrl = "https://picsum.photos/seed/SPRT-007/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 58,  ProductId = 58,  ImageUrl = "https://picsum.photos/seed/SPRT-008/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 59,  ProductId = 59,  ImageUrl = "https://picsum.photos/seed/SPRT-009/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 60,  ProductId = 60,  ImageUrl = "https://picsum.photos/seed/SPRT-010/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 61,  ProductId = 61,  ImageUrl = "https://picsum.photos/seed/BOOK-001/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 62,  ProductId = 62,  ImageUrl = "https://picsum.photos/seed/BOOK-002/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 63,  ProductId = 63,  ImageUrl = "https://picsum.photos/seed/BOOK-003/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 64,  ProductId = 64,  ImageUrl = "https://picsum.photos/seed/BOOK-004/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 65,  ProductId = 65,  ImageUrl = "https://picsum.photos/seed/BOOK-005/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 66,  ProductId = 66,  ImageUrl = "https://picsum.photos/seed/BOOK-006/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 67,  ProductId = 67,  ImageUrl = "https://picsum.photos/seed/BOOK-007/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 68,  ProductId = 68,  ImageUrl = "https://picsum.photos/seed/BOOK-008/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 69,  ProductId = 69,  ImageUrl = "https://picsum.photos/seed/BOOK-009/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 70,  ProductId = 70,  ImageUrl = "https://picsum.photos/seed/BOOK-010/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 71,  ProductId = 71,  ImageUrl = "https://picsum.photos/seed/HLTH-001/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 72,  ProductId = 72,  ImageUrl = "https://picsum.photos/seed/HLTH-002/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 73,  ProductId = 73,  ImageUrl = "https://picsum.photos/seed/HLTH-003/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 74,  ProductId = 74,  ImageUrl = "https://picsum.photos/seed/HLTH-004/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 75,  ProductId = 75,  ImageUrl = "https://picsum.photos/seed/HLTH-005/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 76,  ProductId = 76,  ImageUrl = "https://picsum.photos/seed/HLTH-006/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 77,  ProductId = 77,  ImageUrl = "https://picsum.photos/seed/HLTH-007/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 78,  ProductId = 78,  ImageUrl = "https://picsum.photos/seed/HLTH-008/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 79,  ProductId = 79,  ImageUrl = "https://picsum.photos/seed/HLTH-009/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 80,  ProductId = 80,  ImageUrl = "https://picsum.photos/seed/HLTH-010/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 81,  ProductId = 81,  ImageUrl = "https://picsum.photos/seed/TOYS-001/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 82,  ProductId = 82,  ImageUrl = "https://picsum.photos/seed/TOYS-002/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 83,  ProductId = 83,  ImageUrl = "https://picsum.photos/seed/TOYS-003/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 84,  ProductId = 84,  ImageUrl = "https://picsum.photos/seed/TOYS-004/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 85,  ProductId = 85,  ImageUrl = "https://picsum.photos/seed/TOYS-005/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 86,  ProductId = 86,  ImageUrl = "https://picsum.photos/seed/TOYS-006/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 87,  ProductId = 87,  ImageUrl = "https://picsum.photos/seed/TOYS-007/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 88,  ProductId = 88,  ImageUrl = "https://picsum.photos/seed/TOYS-008/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 89,  ProductId = 89,  ImageUrl = "https://picsum.photos/seed/TOYS-009/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 90,  ProductId = 90,  ImageUrl = "https://picsum.photos/seed/TOYS-010/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 91,  ProductId = 91,  ImageUrl = "https://picsum.photos/seed/FOOD-001/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 92,  ProductId = 92,  ImageUrl = "https://picsum.photos/seed/FOOD-002/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 93,  ProductId = 93,  ImageUrl = "https://picsum.photos/seed/FOOD-003/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 94,  ProductId = 94,  ImageUrl = "https://picsum.photos/seed/FOOD-004/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 95,  ProductId = 95,  ImageUrl = "https://picsum.photos/seed/FOOD-005/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 96,  ProductId = 96,  ImageUrl = "https://picsum.photos/seed/FOOD-006/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 97,  ProductId = 97,  ImageUrl = "https://picsum.photos/seed/FOOD-007/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 98,  ProductId = 98,  ImageUrl = "https://picsum.photos/seed/FOOD-008/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 99,  ProductId = 99,  ImageUrl = "https://picsum.photos/seed/FOOD-009/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now },
            new ProductImage { Id = 100, ProductId = 100, ImageUrl = "https://picsum.photos/seed/FOOD-010/400/400", IsPrimary = true, DisplayOrder = 0, CreatedAt = now }
        );
    }
}
